# Generated by Django 5.1.1 on 2024-09-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_message_property_remove_message_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
